/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, November 15, 2023 at 5:36:37â€¯PM Eastern European Standard Time
* Operating System: Version 17.1 (Build 21B74)
* Image Source: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
* classdump-dyld is licensed under GPLv3, Copyright Â© 2013-2016 by Elias Limneos.
*/

@class NSNumber;

@interface CTSignalStrengthInfo : NSObject <NSCopying, NSSecureCoding> {

	NSNumber* _bars;
	NSNumber* _displayBars;
	NSNumber* _maxDisplayBars;

}

@property (nonatomic,retain) NSNumber * bars;                        //@synthesize bars=_bars - In the implementation block
@property (nonatomic,retain) NSNumber * displayBars;                 //@synthesize displayBars=_displayBars - In the implementation block
@property (nonatomic,retain) NSNumber * maxDisplayBars;              //@synthesize maxDisplayBars=_maxDisplayBars - In the implementation block
+(BOOL)supportsSecureCoding;
-(NSNumber *)bars;
-(void)setDisplayBars:(NSNumber *)arg1 ;
-(void)setMaxDisplayBars:(NSNumber *)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(NSNumber *)maxDisplayBars;
-(void)setBars:(NSNumber *)arg1 ;
-(NSNumber *)displayBars;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
@end
