/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, November 15, 2023 at 5:36:37â€¯PM Eastern European Standard Time
* Operating System: Version 17.1 (Build 21B74)
* Image Source: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
* classdump-dyld is licensed under GPLv3, Copyright Â© 2013-2016 by Elias Limneos.
*/

@class NSUUID, NSString, NSNumber;

@interface CTXPCServiceSubscriptionContext : NSObject <NSCopying, NSSecureCoding> {

	BOOL _isSimPresent;
	BOOL _isSimGood;
	BOOL _isSimHidden;
	BOOL _isSimDataOnly;
	long long _slotID;
	NSUUID* _uuid;
	NSString* _labelID;
	NSString* _label;
	NSString* _phoneNumber;
	NSNumber* _userDataPreferred;
	NSNumber* _userDefaultVoice;

}

@property (nonatomic,retain) NSString * labelID;                        //@synthesize labelID=_labelID - In the implementation block
@property (nonatomic,retain) NSString * label;                          //@synthesize label=_label - In the implementation block
@property (nonatomic,retain) NSString * phoneNumber;                    //@synthesize phoneNumber=_phoneNumber - In the implementation block
@property (nonatomic,retain) NSNumber * userDataPreferred;              //@synthesize userDataPreferred=_userDataPreferred - In the implementation block
@property (nonatomic,retain) NSNumber * userDefaultVoice;               //@synthesize userDefaultVoice=_userDefaultVoice - In the implementation block
@property (assign,nonatomic) BOOL isSimPresent;                         //@synthesize isSimPresent=_isSimPresent - In the implementation block
@property (assign,nonatomic) BOOL isSimGood;                            //@synthesize isSimGood=_isSimGood - In the implementation block
@property (assign,nonatomic) BOOL isSimHidden;                          //@synthesize isSimHidden=_isSimHidden - In the implementation block
@property (assign,nonatomic) BOOL isSimDataOnly;                        //@synthesize isSimDataOnly=_isSimDataOnly - In the implementation block
@property (nonatomic,readonly) long long slotID;                        //@synthesize slotID=_slotID - In the implementation block
@property (nonatomic,readonly) NSUUID * uuid;                           //@synthesize uuid=_uuid - In the implementation block
+(BOOL)supportsSecureCoding;
+(id)contextWithUUID:(id)arg1 ;
+(id)contextWithSlot:(long long)arg1 ;
+(id)contextWithServiceDescriptor:(id)arg1 ;
-(NSUUID *)uuid;
-(BOOL)isSimHidden;
-(NSString *)phoneNumber;
-(void)setPhoneNumber:(NSString *)arg1 ;
-(NSNumber *)userDefaultVoice;
-(id)context;
-(BOOL)isSimGood;
-(void)setUserDataPreferred:(NSNumber *)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(void)setLabel:(NSString *)arg1 ;
-(void)setIsSimPresent:(BOOL)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(void)setIsSimDataOnly:(BOOL)arg1 ;
-(NSString *)labelID;
-(id)initWithCoder:(id)arg1 ;
-(NSString *)label;
-(void)setUserDefaultVoice:(NSNumber *)arg1 ;
-(id)initWithSlot:(long long)arg1 ;
-(NSNumber *)userDataPreferred;
-(id)initWithUUID:(id)arg1 ;
-(long long)slotID;
-(void)setIsSimHidden:(BOOL)arg1 ;
-(id)initWithUUID:(id)arg1 andSlot:(long long)arg2 ;
-(BOOL)isSimDataOnly;
-(id)description;
-(void)setIsSimGood:(BOOL)arg1 ;
-(void)setLabelID:(NSString *)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(BOOL)isSimPresent;
-(id)redactedDescription;
@end

