/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, November 15, 2023 at 5:38:44â€¯PM Eastern European Standard Time
* Operating System: Version 17.1 (Build 21B74)
* Image Source: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
* classdump-dyld is licensed under GPLv3, Copyright Â© 2013-2016 by Elias Limneos.
*/

@protocol MPVolumeControllerDelegate, MPVolumeControllerDataSource;
@class NSString;

@interface MPVolumeController : NSObject {

	int _volumeChangeCoalescingCount;
	id<MPVolumeControllerDelegate> _delegate;
	id<MPVolumeControllerDataSource> _dataSource;

}

@property (getter=isVolumeControlAvailable,nonatomic,readonly) BOOL volumeControlAvailable; 
@property (nonatomic,readonly) unsigned volumeCapabilities; 
@property (nonatomic,copy,readonly) NSString * volumeControlLabel; 
@property (nonatomic,copy) NSString * volumeAudioCategory; 
@property (assign,nonatomic) float volumeValue; 
@property (assign,getter=isMuted,nonatomic) BOOL muted; 
@property (nonatomic,retain) id<MPVolumeControllerDataSource> dataSource;                                //@synthesize dataSource=_dataSource - In the implementation block
@property (nonatomic,readonly) BOOL volumeWarningEnabled; 
@property (nonatomic,readonly) long long volumeWarningState; 
@property (nonatomic,readonly) float EUVolumeLimit; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)descriptionForWarningState:(long long)arg1 ;
-(unsigned)volumeCapabilities;
-(NSString *)volumeAudioCategory;
-(void)decreaseVolume;
-(void)setVolumeAudioCategory:(NSString *)arg1 ;
-(id)initWithDataSource:(id)arg1 ;
-(void)volumeControllerDataSource:(id)arg1 didChangeVolumeControlAvailability:(BOOL)arg2 ;
-(void)adjustVolumeValue:(float)arg1 ;
-(NSString *)volumeControlLabel;
-(void)updateVolumeValue;
-(void)endIncreasingRelativeVolume;
-(void)volumeControllerDataSource:(id)arg1 didChangeVolume:(float)arg2 ;
-(void)beginDecreasingRelativeVolume;
-(BOOL)volumeWarningEnabled;
-(void)endDecreasingRelativeVolume;
-(void)increaseVolume;
-(long long)volumeWarningState;
-(void)setMuted:(BOOL)arg1 ;
-(id<MPVolumeControllerDataSource>)dataSource;
-(void)setDelegate:(id<MPVolumeControllerDelegate>)arg1 ;
-(void)volumeControllerDataSource:(id)arg1 didChangeVolume:(float)arg2 silenceVolumeHUD:(BOOL)arg3 ;
-(void)updateVolumeWarningState;
-(BOOL)isVolumeControlAvailable;
-(id)init;
-(void)setVolume:(float)arg1 withNoticationDelay:(float)arg2 ;
-(id<MPVolumeControllerDelegate>)delegate;
-(void)setDataSource:(id<MPVolumeControllerDataSource>)arg1 ;
-(void)setVolumeValue:(float)arg1 ;
-(void)getVolumeValueWithCompletion:(/*^block*/id)arg1 ;
-(BOOL)isMuted;
-(float)EUVolumeLimit;
-(void)volumeControllerDataSource:(id)arg1 didChangeMuted:(BOOL)arg2 ;
-(void)setVolume:(float)arg1 withNotificationDelay:(float)arg2 ;
-(void)volumeControllerDataSource:(id)arg1 didChangeVolumeAudioCategory:(id)arg2 ;
-(float)volumeValue;
-(BOOL)muted;
-(void)volumeControllerDataSource:(id)arg1 didChangeVolumeLabel:(id)arg2 ;
-(void)volumeControllerDataSource:(id)arg1 didChangeVolumeCapabilities:(unsigned)arg2 ;
-(void)beginIncreasingRelativeVolume;
@end

