/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, November 15, 2023 at 5:38:40â€¯PM Eastern European Standard Time
* Operating System: Version 17.1 (Build 21B74)
* Image Source: /System/Library/PrivateFrameworks/MediaRemote.framework/MediaRemote
* classdump-dyld is licensed under GPLv3, Copyright Â© 2013-2016 by Elias Limneos.
*/

@class NSData, NSDictionary;

@interface MRArtwork : NSObject <NSCopying> {

	NSData* _imageData;
	long long _height;
	long long _width;

}

@property (nonatomic,copy) NSData * imageData;                                            //@synthesize imageData=_imageData - In the implementation block
@property (assign,nonatomic) long long height;                                            //@synthesize height=_height - In the implementation block
@property (assign,nonatomic) long long width;                                             //@synthesize width=_width - In the implementation block
@property (nonatomic,copy,readonly) NSDictionary * dictionaryRepresentation; 
+(BOOL)processRequestsExternalArtworkValidation;
-(NSData *)imageData;
-(id)artworkByResizingWithWidth:(long long)arg1 height:(long long)arg2 ;
-(void)setHeight:(long long)arg1 ;
-(id)initWithImageData:(id)arg1 height:(long long)arg2 width:(long long)arg3 ;
-(id)initWithProtobuf:(id)arg1 ;
-(NSDictionary *)dictionaryRepresentation;
-(void)setImageData:(NSData *)arg1 ;
-(void)setWidth:(long long)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(long long)height;
-(long long)width;
-(id)debugDescription;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
@end

