/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, November 15, 2023 at 5:38:40â€¯PM Eastern European Standard Time
* Operating System: Version 17.1 (Build 21B74)
* Image Source: /System/Library/PrivateFrameworks/MediaRemote.framework/MediaRemote
* classdump-dyld is licensed under GPLv3, Copyright Â© 2013-2016 by Elias Limneos.
*/

@class NSData, NSDictionary, NSDate, NSString, NSURL, NSArray, MRContentItemMetadataAudioFormat, MRContentItemMetadataAudioRoute;

@interface MRContentItemMetadata : NSObject <NSCopying> {

	BOOL _container;
	BOOL _hasContainer;
	BOOL _playable;
	BOOL _hasPlayable;
	BOOL _explicitItem;
	BOOL _hasExplicitItem;
	BOOL _streamingContent;
	BOOL _hasStreamingContent;
	BOOL _currentlyPlaying;
	BOOL _hasCurrentlyPlaying;
	BOOL _alwaysLive;
	BOOL _hasAlwaysLive;
	BOOL _sharable;
	BOOL _hasSharable;
	BOOL _liked;
	BOOL _hasLiked;
	BOOL _inWishList;
	BOOL _hasInWishList;
	BOOL _advertisement;
	BOOL _hasAdvertisement;
	BOOL _steerable;
	BOOL _hasSteerable;
	BOOL _loading;
	BOOL _hasLoading;
	BOOL _artworkAvailable;
	BOOL _hasArtworkAvailable;
	BOOL _infoAvailable;
	BOOL _hasInfoAvailable;
	BOOL _languageOptionsAvailable;
	BOOL _hasLanguageOptionsAvailable;
	BOOL _lyricsAvailable;
	BOOL _hasLyricsAvailable;
	BOOL _hasPlaybackProgress;
	BOOL _hasPlaybackRate;
	BOOL _hasDefaultPlaybackRate;
	BOOL _hasDownloadProgress;
	BOOL _hasPlaylistType;
	BOOL _hasRadioStationType;
	BOOL _hasEditingStyleFlags;
	BOOL _hasMediaType;
	BOOL _hasMediaSubType;
	BOOL _hasEpisodeType;
	BOOL _hasPlayCount;
	BOOL _hasNumberOfSections;
	BOOL _hasChapterCount;
	BOOL _hasTotalDiscCount;
	BOOL _hasTotalTrackCount;
	BOOL _hasDownloadState;
	BOOL _hasArtworkDataWidthDeprecated;
	BOOL _hasArtworkDataHeightDeprecated;
	BOOL _hasDuration;
	BOOL _hasStartTime;
	BOOL _hasElapsedTime;
	BOOL _hasElapsedTimeTimestamp;
	BOOL _hasInferredTimestamp;
	BOOL _hasSeasonNumber;
	BOOL _hasEpisodeNumber;
	BOOL _hasDiscNumber;
	BOOL _hasTrackNumber;
	BOOL _hasRadioStationIdentifier;
	BOOL _hasITunesStoreIdentifier;
	BOOL _hasITunesStoreSubscriptionIdentifier;
	BOOL _hasITunesStoreArtistIdentifier;
	BOOL _hasITunesStoreAlbumIdentifier;
	BOOL _hasLegacyUniqueIdentifier;
	BOOL _hasIsResolvableParticipant;
	BOOL _isResolvableParticipant;
	BOOL _hasReportingAdamID;
	BOOL _hasLyricsAdamID;
	BOOL _hasITunesStoreAlbumArtistIdentifier;
	BOOL _hasSongTraits;
	BOOL _hasAlbumTraits;
	BOOL _hasPlaylistTraits;
	BOOL _hasActiveFormatJustification;
	BOOL _hasFormatTierPreference;
	float _playbackProgress;
	float _playbackRate;
	float _defaultPlaybackRate;
	float _downloadProgress;
	long long _playlistType;
	long long _radioStationType;
	long long _editingStyleFlags;
	long long _mediaType;
	long long _mediaSubType;
	long long _episodeType;
	long long _playCount;
	long long _numberOfSections;
	long long _chapterCount;
	long long _totalDiscCount;
	long long _totalTrackCount;
	long long _downloadState;
	long long _artworkDataWidthDeprecated;
	long long _artworkDataHeightDeprecated;
	double _duration;
	double _startTime;
	double _elapsedTime;
	double _elapsedTimeTimestamp;
	double _inferredTimestamp;
	long long _seasonNumber;
	long long _episodeNumber;
	long long _discNumber;
	long long _trackNumber;
	long long _radioStationIdentifier;
	long long _iTunesStoreIdentifier;
	long long _iTunesStoreSubscriptionIdentifier;
	long long _iTunesStoreArtistIdentifier;
	long long _iTunesStoreAlbumIdentifier;
	long long _legacyUniqueIdentifier;
	NSData* _purchaseInfoData;
	NSDictionary* _appMetrics;
	NSDictionary* _nowPlayingInfo;
	NSDictionary* _userInfo;
	NSDictionary* _deviceSpecificUserInfo;
	NSDictionary* _collectionInfo;
	NSDate* _releaseDate;
	NSDate* _currentPlaybackDate;
	NSString* _title;
	NSString* _subtitle;
	NSString* _classicalWork;
	NSString* _albumName;
	NSString* _trackArtistName;
	NSString* _albumArtistName;
	NSString* _directorName;
	NSString* _localizedContentRating;
	NSString* _collectionIdentifier;
	NSString* _profileIdentifier;
	NSURL* _assetURL;
	NSString* _composer;
	NSString* _genre;
	NSString* _contentIdentifier;
	NSString* _radioStationName;
	NSString* _radioStationString;
	NSString* _seriesName;
	NSURL* _lyricsURL;
	NSString* _serviceIdentifier;
	NSString* _brandIdentifier;
	NSString* _durationStringLocalizationKey;
	NSString* _localizedDurationString;
	NSString* _artworkIdentifier;
	NSString* _artworkMIMEType;
	NSURL* _artworkURL;
	NSURL* _artworkFileURL;
	NSArray* _artworkURLTemplates;
	NSString* _albumYear;
	NSString* _participantName;
	NSString* _participantIdentifier;
	long long _reportingAdamID;
	long long _lyricsAdamID;
	long long _iTunesStoreAlbumArtistIdentifier;
	unsigned long long _songTraits;
	unsigned long long _albumTraits;
	unsigned long long _playlistTraits;
	MRContentItemMetadataAudioFormat* _preferredFormat;
	MRContentItemMetadataAudioFormat* _activeFormat;
	long long _activeFormatJustification;
	unsigned long long _formatTierPreference;
	MRContentItemMetadataAudioRoute* _audioRoute;
	NSArray* _alternativeFormats;

}

@property (assign,nonatomic) double elapsedTimeTimestamp;                                   //@synthesize elapsedTimeTimestamp=_elapsedTimeTimestamp - In the implementation block
@property (assign,nonatomic) BOOL hasElapsedTimeTimestamp;                                  //@synthesize hasElapsedTimeTimestamp=_hasElapsedTimeTimestamp - In the implementation block
@property (assign,nonatomic) double inferredTimestamp;                                      //@synthesize inferredTimestamp=_inferredTimestamp - In the implementation block
@property (assign,nonatomic) BOOL hasInferredTimestamp;                                     //@synthesize hasInferredTimestamp=_hasInferredTimestamp - In the implementation block
@property (assign,getter=isContainer,nonatomic) BOOL container;                             //@synthesize container=_container - In the implementation block
@property (assign,nonatomic) BOOL hasContainer;                                             //@synthesize hasContainer=_hasContainer - In the implementation block
@property (assign,getter=isPlayable,nonatomic) BOOL playable;                               //@synthesize playable=_playable - In the implementation block
@property (assign,nonatomic) BOOL hasPlayable;                                              //@synthesize hasPlayable=_hasPlayable - In the implementation block
@property (assign,getter=isExplicitItem,nonatomic) BOOL explicitItem;                       //@synthesize explicitItem=_explicitItem - In the implementation block
@property (assign,nonatomic) BOOL hasExplicitItem;                                          //@synthesize hasExplicitItem=_hasExplicitItem - In the implementation block
@property (assign,getter=isStreamingContent,nonatomic) BOOL streamingContent;               //@synthesize streamingContent=_streamingContent - In the implementation block
@property (assign,nonatomic) BOOL hasStreamingContent;                                      //@synthesize hasStreamingContent=_hasStreamingContent - In the implementation block
@property (assign,getter=isCurrentlyPlaying,nonatomic) BOOL currentlyPlaying;               //@synthesize currentlyPlaying=_currentlyPlaying - In the implementation block
@property (assign,nonatomic) BOOL hasCurrentlyPlaying;                                      //@synthesize hasCurrentlyPlaying=_hasCurrentlyPlaying - In the implementation block
@property (assign,getter=isAlwaysLive,nonatomic) BOOL alwaysLive;                           //@synthesize alwaysLive=_alwaysLive - In the implementation block
@property (assign,nonatomic) BOOL hasAlwaysLive;                                            //@synthesize hasAlwaysLive=_hasAlwaysLive - In the implementation block
@property (assign,getter=isSharable,nonatomic) BOOL sharable;                               //@synthesize sharable=_sharable - In the implementation block
@property (assign,nonatomic) BOOL hasSharable;                                              //@synthesize hasSharable=_hasSharable - In the implementation block
@property (assign,getter=isLiked,nonatomic) BOOL liked;                                     //@synthesize liked=_liked - In the implementation block
@property (assign,nonatomic) BOOL hasLiked;                                                 //@synthesize hasLiked=_hasLiked - In the implementation block
@property (assign,getter=isInWishList,nonatomic) BOOL inWishList;                           //@synthesize inWishList=_inWishList - In the implementation block
@property (assign,nonatomic) BOOL hasInWishList;                                            //@synthesize hasInWishList=_hasInWishList - In the implementation block
@property (assign,getter=isAdvertisement,nonatomic) BOOL advertisement;                     //@synthesize advertisement=_advertisement - In the implementation block
@property (assign,nonatomic) BOOL hasAdvertisement;                                         //@synthesize hasAdvertisement=_hasAdvertisement - In the implementation block
@property (assign,getter=isSteerable,nonatomic) BOOL steerable;                             //@synthesize steerable=_steerable - In the implementation block
@property (assign,nonatomic) BOOL hasSteerable;                                             //@synthesize hasSteerable=_hasSteerable - In the implementation block
@property (assign,getter=isLoading,nonatomic) BOOL loading;                                 //@synthesize loading=_loading - In the implementation block
@property (assign,nonatomic) BOOL hasLoading;                                               //@synthesize hasLoading=_hasLoading - In the implementation block
@property (assign,nonatomic) BOOL artworkAvailable;                                         //@synthesize artworkAvailable=_artworkAvailable - In the implementation block
@property (assign,nonatomic) BOOL hasArtworkAvailable;                                      //@synthesize hasArtworkAvailable=_hasArtworkAvailable - In the implementation block
@property (assign,nonatomic) BOOL infoAvailable;                                            //@synthesize infoAvailable=_infoAvailable - In the implementation block
@property (assign,nonatomic) BOOL hasInfoAvailable;                                         //@synthesize hasInfoAvailable=_hasInfoAvailable - In the implementation block
@property (assign,nonatomic) BOOL languageOptionsAvailable;                                 //@synthesize languageOptionsAvailable=_languageOptionsAvailable - In the implementation block
@property (assign,nonatomic) BOOL hasLanguageOptionsAvailable;                              //@synthesize hasLanguageOptionsAvailable=_hasLanguageOptionsAvailable - In the implementation block
@property (assign,nonatomic) BOOL lyricsAvailable;                                          //@synthesize lyricsAvailable=_lyricsAvailable - In the implementation block
@property (assign,nonatomic) BOOL hasLyricsAvailable;                                       //@synthesize hasLyricsAvailable=_hasLyricsAvailable - In the implementation block
@property (assign,nonatomic) float playbackProgress;                                        //@synthesize playbackProgress=_playbackProgress - In the implementation block
@property (assign,nonatomic) BOOL hasPlaybackProgress;                                      //@synthesize hasPlaybackProgress=_hasPlaybackProgress - In the implementation block
@property (assign,nonatomic) float playbackRate;                                            //@synthesize playbackRate=_playbackRate - In the implementation block
@property (assign,nonatomic) BOOL hasPlaybackRate;                                          //@synthesize hasPlaybackRate=_hasPlaybackRate - In the implementation block
@property (assign,nonatomic) float defaultPlaybackRate;                                     //@synthesize defaultPlaybackRate=_defaultPlaybackRate - In the implementation block
@property (assign,nonatomic) BOOL hasDefaultPlaybackRate;                                   //@synthesize hasDefaultPlaybackRate=_hasDefaultPlaybackRate - In the implementation block
@property (assign,nonatomic) float downloadProgress;                                        //@synthesize downloadProgress=_downloadProgress - In the implementation block
@property (assign,nonatomic) BOOL hasDownloadProgress;                                      //@synthesize hasDownloadProgress=_hasDownloadProgress - In the implementation block
@property (assign,nonatomic) long long playlistType;                                        //@synthesize playlistType=_playlistType - In the implementation block
@property (assign,nonatomic) BOOL hasPlaylistType;                                          //@synthesize hasPlaylistType=_hasPlaylistType - In the implementation block
@property (assign,nonatomic) long long radioStationType;                                    //@synthesize radioStationType=_radioStationType - In the implementation block
@property (assign,nonatomic) BOOL hasRadioStationType;                                      //@synthesize hasRadioStationType=_hasRadioStationType - In the implementation block
@property (assign,nonatomic) long long editingStyleFlags;                                   //@synthesize editingStyleFlags=_editingStyleFlags - In the implementation block
@property (assign,nonatomic) BOOL hasEditingStyleFlags;                                     //@synthesize hasEditingStyleFlags=_hasEditingStyleFlags - In the implementation block
@property (assign,nonatomic) long long mediaType;                                           //@synthesize mediaType=_mediaType - In the implementation block
@property (assign,nonatomic) BOOL hasMediaType;                                             //@synthesize hasMediaType=_hasMediaType - In the implementation block
@property (assign,nonatomic) long long mediaSubType;                                        //@synthesize mediaSubType=_mediaSubType - In the implementation block
@property (assign,nonatomic) BOOL hasMediaSubType;                                          //@synthesize hasMediaSubType=_hasMediaSubType - In the implementation block
@property (assign,nonatomic) long long episodeType;                                         //@synthesize episodeType=_episodeType - In the implementation block
@property (assign,nonatomic) BOOL hasEpisodeType;                                           //@synthesize hasEpisodeType=_hasEpisodeType - In the implementation block
@property (assign,nonatomic) long long playCount;                                           //@synthesize playCount=_playCount - In the implementation block
@property (assign,nonatomic) BOOL hasPlayCount;                                             //@synthesize hasPlayCount=_hasPlayCount - In the implementation block
@property (assign,nonatomic) long long numberOfSections;                                    //@synthesize numberOfSections=_numberOfSections - In the implementation block
@property (assign,nonatomic) BOOL hasNumberOfSections;                                      //@synthesize hasNumberOfSections=_hasNumberOfSections - In the implementation block
@property (assign,nonatomic) long long chapterCount;                                        //@synthesize chapterCount=_chapterCount - In the implementation block
@property (assign,nonatomic) BOOL hasChapterCount;                                          //@synthesize hasChapterCount=_hasChapterCount - In the implementation block
@property (assign,nonatomic) long long totalDiscCount;                                      //@synthesize totalDiscCount=_totalDiscCount - In the implementation block
@property (assign,nonatomic) BOOL hasTotalDiscCount;                                        //@synthesize hasTotalDiscCount=_hasTotalDiscCount - In the implementation block
@property (assign,nonatomic) long long totalTrackCount;                                     //@synthesize totalTrackCount=_totalTrackCount - In the implementation block
@property (assign,nonatomic) BOOL hasTotalTrackCount;                                       //@synthesize hasTotalTrackCount=_hasTotalTrackCount - In the implementation block
@property (assign,nonatomic) long long downloadState;                                       //@synthesize downloadState=_downloadState - In the implementation block
@property (assign,nonatomic) BOOL hasDownloadState;                                         //@synthesize hasDownloadState=_hasDownloadState - In the implementation block
@property (assign,nonatomic) double duration;                                               //@synthesize duration=_duration - In the implementation block
@property (assign,nonatomic) BOOL hasDuration;                                              //@synthesize hasDuration=_hasDuration - In the implementation block
@property (assign,nonatomic) double startTime;                                              //@synthesize startTime=_startTime - In the implementation block
@property (assign,nonatomic) BOOL hasStartTime;                                             //@synthesize hasStartTime=_hasStartTime - In the implementation block
@property (assign,nonatomic) double elapsedTime;                                            //@synthesize elapsedTime=_elapsedTime - In the implementation block
@property (assign,nonatomic) BOOL hasElapsedTime;                                           //@synthesize hasElapsedTime=_hasElapsedTime - In the implementation block
@property (assign,nonatomic) long long seasonNumber;                                        //@synthesize seasonNumber=_seasonNumber - In the implementation block
@property (assign,nonatomic) BOOL hasSeasonNumber;                                          //@synthesize hasSeasonNumber=_hasSeasonNumber - In the implementation block
@property (assign,nonatomic) long long episodeNumber;                                       //@synthesize episodeNumber=_episodeNumber - In the implementation block
@property (assign,nonatomic) BOOL hasEpisodeNumber;                                         //@synthesize hasEpisodeNumber=_hasEpisodeNumber - In the implementation block
@property (assign,nonatomic) long long discNumber;                                          //@synthesize discNumber=_discNumber - In the implementation block
@property (assign,nonatomic) BOOL hasDiscNumber;                                            //@synthesize hasDiscNumber=_hasDiscNumber - In the implementation block
@property (assign,nonatomic) long long trackNumber;                                         //@synthesize trackNumber=_trackNumber - In the implementation block
@property (assign,nonatomic) BOOL hasTrackNumber;                                           //@synthesize hasTrackNumber=_hasTrackNumber - In the implementation block
@property (assign,nonatomic) long long radioStationIdentifier;                              //@synthesize radioStationIdentifier=_radioStationIdentifier - In the implementation block
@property (assign,nonatomic) BOOL hasRadioStationIdentifier;                                //@synthesize hasRadioStationIdentifier=_hasRadioStationIdentifier - In the implementation block
@property (assign,nonatomic) long long iTunesStoreIdentifier;                               //@synthesize iTunesStoreIdentifier=_iTunesStoreIdentifier - In the implementation block
@property (assign,nonatomic) BOOL hasITunesStoreIdentifier;                                 //@synthesize hasITunesStoreIdentifier=_hasITunesStoreIdentifier - In the implementation block
@property (assign,nonatomic) long long iTunesStoreSubscriptionIdentifier;                   //@synthesize iTunesStoreSubscriptionIdentifier=_iTunesStoreSubscriptionIdentifier - In the implementation block
@property (assign,nonatomic) BOOL hasITunesStoreSubscriptionIdentifier;                     //@synthesize hasITunesStoreSubscriptionIdentifier=_hasITunesStoreSubscriptionIdentifier - In the implementation block
@property (assign,nonatomic) long long iTunesStoreArtistIdentifier;                         //@synthesize iTunesStoreArtistIdentifier=_iTunesStoreArtistIdentifier - In the implementation block
@property (assign,nonatomic) BOOL hasITunesStoreArtistIdentifier;                           //@synthesize hasITunesStoreArtistIdentifier=_hasITunesStoreArtistIdentifier - In the implementation block
@property (assign,nonatomic) long long iTunesStoreAlbumIdentifier;                          //@synthesize iTunesStoreAlbumIdentifier=_iTunesStoreAlbumIdentifier - In the implementation block
@property (assign,nonatomic) BOOL hasITunesStoreAlbumIdentifier;                            //@synthesize hasITunesStoreAlbumIdentifier=_hasITunesStoreAlbumIdentifier - In the implementation block
@property (assign,nonatomic) long long legacyUniqueIdentifier;                              //@synthesize legacyUniqueIdentifier=_legacyUniqueIdentifier - In the implementation block
@property (assign,nonatomic) BOOL hasLegacyUniqueIdentifier;                                //@synthesize hasLegacyUniqueIdentifier=_hasLegacyUniqueIdentifier - In the implementation block
@property (nonatomic,copy) NSData * purchaseInfoData;                                       //@synthesize purchaseInfoData=_purchaseInfoData - In the implementation block
@property (nonatomic,copy) NSDictionary * appMetrics;                                       //@synthesize appMetrics=_appMetrics - In the implementation block
@property (nonatomic,copy) NSDictionary * nowPlayingInfo;                                   //@synthesize nowPlayingInfo=_nowPlayingInfo - In the implementation block
@property (nonatomic,copy) NSDictionary * userInfo;                                         //@synthesize userInfo=_userInfo - In the implementation block
@property (nonatomic,copy) NSDictionary * deviceSpecificUserInfo;                           //@synthesize deviceSpecificUserInfo=_deviceSpecificUserInfo - In the implementation block
@property (nonatomic,copy) NSDictionary * collectionInfo;                                   //@synthesize collectionInfo=_collectionInfo - In the implementation block
@property (nonatomic,copy) NSDate * releaseDate;                                            //@synthesize releaseDate=_releaseDate - In the implementation block
@property (nonatomic,copy) NSDate * currentPlaybackDate;                                    //@synthesize currentPlaybackDate=_currentPlaybackDate - In the implementation block
@property (nonatomic,copy) NSString * title;                                                //@synthesize title=_title - In the implementation block
@property (nonatomic,copy) NSString * subtitle;                                             //@synthesize subtitle=_subtitle - In the implementation block
@property (nonatomic,copy) NSString * classicalWork;                                        //@synthesize classicalWork=_classicalWork - In the implementation block
@property (nonatomic,copy) NSString * albumName;                                            //@synthesize albumName=_albumName - In the implementation block
@property (nonatomic,copy) NSString * trackArtistName;                                      //@synthesize trackArtistName=_trackArtistName - In the implementation block
@property (nonatomic,copy) NSString * albumArtistName;                                      //@synthesize albumArtistName=_albumArtistName - In the implementation block
@property (nonatomic,copy) NSString * directorName;                                         //@synthesize directorName=_directorName - In the implementation block
@property (nonatomic,copy) NSString * localizedContentRating;                               //@synthesize localizedContentRating=_localizedContentRating - In the implementation block
@property (nonatomic,copy) NSString * collectionIdentifier;                                 //@synthesize collectionIdentifier=_collectionIdentifier - In the implementation block
@property (nonatomic,copy) NSString * profileIdentifier;                                    //@synthesize profileIdentifier=_profileIdentifier - In the implementation block
@property (nonatomic,copy) NSURL * assetURL;                                                //@synthesize assetURL=_assetURL - In the implementation block
@property (nonatomic,copy) NSString * composer;                                             //@synthesize composer=_composer - In the implementation block
@property (nonatomic,copy) NSString * genre;                                                //@synthesize genre=_genre - In the implementation block
@property (nonatomic,copy) NSString * contentIdentifier;                                    //@synthesize contentIdentifier=_contentIdentifier - In the implementation block
@property (nonatomic,copy) NSString * radioStationName;                                     //@synthesize radioStationName=_radioStationName - In the implementation block
@property (nonatomic,copy) NSString * radioStationString;                                   //@synthesize radioStationString=_radioStationString - In the implementation block
@property (nonatomic,copy) NSString * seriesName;                                           //@synthesize seriesName=_seriesName - In the implementation block
@property (nonatomic,copy) NSURL * lyricsURL;                                               //@synthesize lyricsURL=_lyricsURL - In the implementation block
@property (nonatomic,copy) NSString * serviceIdentifier;                                    //@synthesize serviceIdentifier=_serviceIdentifier - In the implementation block
@property (nonatomic,copy) NSString * brandIdentifier;                                      //@synthesize brandIdentifier=_brandIdentifier - In the implementation block
@property (nonatomic,copy) NSString * localizedDurationString;                              //@synthesize localizedDurationString=_localizedDurationString - In the implementation block
@property (nonatomic,copy) NSString * durationStringLocalizationKey;                        //@synthesize durationStringLocalizationKey=_durationStringLocalizationKey - In the implementation block
@property (nonatomic,copy) NSString * artworkIdentifier;                                    //@synthesize artworkIdentifier=_artworkIdentifier - In the implementation block
@property (nonatomic,copy) NSString * artworkMIMEType;                                      //@synthesize artworkMIMEType=_artworkMIMEType - In the implementation block
@property (nonatomic,copy) NSURL * artworkURL;                                              //@synthesize artworkURL=_artworkURL - In the implementation block
@property (nonatomic,copy) NSURL * artworkFileURL;                                          //@synthesize artworkFileURL=_artworkFileURL - In the implementation block
@property (nonatomic,copy) NSArray * artworkURLTemplates;                                   //@synthesize artworkURLTemplates=_artworkURLTemplates - In the implementation block
@property (nonatomic,copy) NSString * albumYear;                                            //@synthesize albumYear=_albumYear - In the implementation block
@property (nonatomic,copy) NSString * participantName;                                      //@synthesize participantName=_participantName - In the implementation block
@property (nonatomic,copy) NSString * participantIdentifier;                                //@synthesize participantIdentifier=_participantIdentifier - In the implementation block
@property (assign,nonatomic) BOOL isResolvableParticipant;                                  //@synthesize isResolvableParticipant=_isResolvableParticipant - In the implementation block
@property (assign,nonatomic) unsigned long long songTraits;                                 //@synthesize songTraits=_songTraits - In the implementation block
@property (assign,nonatomic) BOOL hasSongTraits;                                            //@synthesize hasSongTraits=_hasSongTraits - In the implementation block
@property (assign,nonatomic) unsigned long long albumTraits;                                //@synthesize albumTraits=_albumTraits - In the implementation block
@property (assign,nonatomic) BOOL hasAlbumTraits;                                           //@synthesize hasAlbumTraits=_hasAlbumTraits - In the implementation block
@property (assign,nonatomic) unsigned long long playlistTraits;                             //@synthesize playlistTraits=_playlistTraits - In the implementation block
@property (assign,nonatomic) BOOL hasPlaylistTraits;                                        //@synthesize hasPlaylistTraits=_hasPlaylistTraits - In the implementation block
@property (nonatomic,copy) MRContentItemMetadataAudioFormat * preferredFormat;              //@synthesize preferredFormat=_preferredFormat - In the implementation block
@property (nonatomic,copy) MRContentItemMetadataAudioFormat * activeFormat;                 //@synthesize activeFormat=_activeFormat - In the implementation block
@property (assign,nonatomic) long long activeFormatJustification;                           //@synthesize activeFormatJustification=_activeFormatJustification - In the implementation block
@property (assign,nonatomic) BOOL hasActiveFormatJustification;                             //@synthesize hasActiveFormatJustification=_hasActiveFormatJustification - In the implementation block
@property (assign,nonatomic) unsigned long long formatTierPreference;                       //@synthesize formatTierPreference=_formatTierPreference - In the implementation block
@property (assign,nonatomic) BOOL hasFormatTierPreference;                                  //@synthesize hasFormatTierPreference=_hasFormatTierPreference - In the implementation block
@property (nonatomic,copy) MRContentItemMetadataAudioRoute * audioRoute;                    //@synthesize audioRoute=_audioRoute - In the implementation block
@property (nonatomic,copy) NSArray * alternativeFormats;                                    //@synthesize alternativeFormats=_alternativeFormats - In the implementation block
@property (nonatomic,copy,readonly) NSData * data; 
@property (assign,nonatomic) long long reportingAdamID;                                     //@synthesize reportingAdamID=_reportingAdamID - In the implementation block
@property (assign,nonatomic) BOOL hasReportingAdamID;                                       //@synthesize hasReportingAdamID=_hasReportingAdamID - In the implementation block
@property (assign,nonatomic) long long lyricsAdamID;                                        //@synthesize lyricsAdamID=_lyricsAdamID - In the implementation block
@property (assign,nonatomic) BOOL hasLyricsAdamID;                                          //@synthesize hasLyricsAdamID=_hasLyricsAdamID - In the implementation block
@property (assign,nonatomic) long long iTunesStoreAlbumArtistIdentifier;                    //@synthesize iTunesStoreAlbumArtistIdentifier=_iTunesStoreAlbumArtistIdentifier - In the implementation block
@property (assign,nonatomic) BOOL hasITunesStoreAlbumArtistIdentifier;                      //@synthesize hasITunesStoreAlbumArtistIdentifier=_hasITunesStoreAlbumArtistIdentifier - In the implementation block
@property (nonatomic,readonly) long long artworkDataWidthDeprecated;                        //@synthesize artworkDataWidthDeprecated=_artworkDataWidthDeprecated - In the implementation block
@property (nonatomic,readonly) BOOL hasArtworkDataWidthDeprecated;                          //@synthesize hasArtworkDataWidthDeprecated=_hasArtworkDataWidthDeprecated - In the implementation block
@property (nonatomic,readonly) long long artworkDataHeightDeprecated;                       //@synthesize artworkDataHeightDeprecated=_artworkDataHeightDeprecated - In the implementation block
@property (nonatomic,readonly) BOOL hasArtworkDataHeightDeprecated;                         //@synthesize hasArtworkDataHeightDeprecated=_hasArtworkDataHeightDeprecated - In the implementation block
@property (nonatomic,copy,readonly) NSString * localizedTitle; 
@property (nonatomic,readonly) BOOL hasLoadingPlaceholderTitle; 
@property (nonatomic,readonly) BOOL hasIsResolvableParticipant;                             //@synthesize hasIsResolvableParticipant=_hasIsResolvableParticipant - In the implementation block
@property (nonatomic,readonly) double calculatedPlaybackPosition; 
@property (nonatomic,readonly) NSDictionary * dictionaryRepresentation; 
-(long long)totalDiscCount;
-(void)setPlaybackProgress:(float)arg1 ;
-(void)setLyricsAvailable:(BOOL)arg1 ;
-(void)setHasDownloadState:(BOOL)arg1 ;
-(long long)reportingAdamID;
-(BOOL)isLiked;
-(BOOL)isSteerable;
-(void)setHasLyricsAvailable:(BOOL)arg1 ;
-(void)setReleaseDate:(NSDate *)arg1 ;
-(BOOL)hasSeasonNumber;
-(NSString *)participantIdentifier;
-(void)setDiscNumber:(long long)arg1 ;
-(BOOL)hasElapsedTime;
-(MRContentItemMetadataAudioRoute *)audioRoute;
-(float)playbackRate;
-(void)setAlbumArtistName:(NSString *)arg1 ;
-(BOOL)hasDuration;
-(void)setHasInferredTimestamp:(BOOL)arg1 ;
-(NSString *)brandIdentifier;
-(BOOL)hasLegacyUniqueIdentifier;
-(unsigned long long)songTraits;
-(long long)mediaSubType;
-(BOOL)hasPlayable;
-(long long)episodeType;
-(float)playbackProgress;
-(void)setSeasonNumber:(long long)arg1 ;
-(void)setArtworkIdentifier:(NSString *)arg1 ;
-(void)setLyricsAdamID:(long long)arg1 ;
-(BOOL)hasLanguageOptionsAvailable;
-(long long)playCount;
-(long long)downloadState;
-(BOOL)hasDownloadProgress;
-(void)setHasPlaybackProgress:(BOOL)arg1 ;
-(void)setHasEpisodeType:(BOOL)arg1 ;
-(void)setArtworkAvailable:(BOOL)arg1 ;
-(void)setElapsedTime:(double)arg1 ;
-(NSString *)trackArtistName;
-(void)setHasSeasonNumber:(BOOL)arg1 ;
-(NSString *)artworkIdentifier;
-(void)setPlayable:(BOOL)arg1 ;
-(void)setMediaType:(long long)arg1 ;
-(void)setEpisodeType:(long long)arg1 ;
-(void)setSongTraits:(unsigned long long)arg1 ;
-(NSURL *)lyricsURL;
-(BOOL)artworkAvailable;
-(long long)iTunesStoreArtistIdentifier;
-(BOOL)hasTrackNumber;
-(void)setReportingAdamID:(long long)arg1 ;
-(BOOL)hasPlaylistType;
-(long long)numberOfSections;
-(NSString *)radioStationName;
-(void)setAlbumTraits:(unsigned long long)arg1 ;
-(void)setPlayCount:(long long)arg1 ;
-(double)elapsedTime;
-(NSString *)albumArtistName;
-(void)setGenre:(NSString *)arg1 ;
-(void)setPurchaseInfoData:(NSData *)arg1 ;
-(NSDictionary *)nowPlayingInfo;
-(long long)trackNumber;
-(BOOL)hasMediaSubType;
-(void)setTrackArtistName:(NSString *)arg1 ;
-(void)setHasAlbumTraits:(BOOL)arg1 ;
-(void)setArtworkMIMEType:(NSString *)arg1 ;
-(void)setFormatTierPreference:(unsigned long long)arg1 ;
-(void)setHasMediaType:(BOOL)arg1 ;
-(BOOL)hasNumberOfSections;
-(BOOL)isInWishList;
-(long long)playlistType;
-(void)setArtworkURL:(NSURL *)arg1 ;
-(BOOL)hasChapterCount;
-(void)setTrackNumber:(long long)arg1 ;
-(void)setDirectorName:(NSString *)arg1 ;
-(void)setHasPlayCount:(BOOL)arg1 ;
-(BOOL)isAlwaysLive;
-(long long)iTunesStoreIdentifier;
-(NSString *)genre;
-(BOOL)isContainer;
-(void)setComposer:(NSString *)arg1 ;
-(void)setContainer:(BOOL)arg1 ;
-(BOOL)hasITunesStoreIdentifier;
-(NSString *)serviceIdentifier;
-(NSString *)localizedTitle;
-(BOOL)hasMediaType;
-(void)setCollectionIdentifier:(NSString *)arg1 ;
-(BOOL)hasEditingStyleFlags;
-(BOOL)isLoading;
-(BOOL)hasStartTime;
-(void)setServiceIdentifier:(NSString *)arg1 ;
-(void)setExplicitItem:(BOOL)arg1 ;
-(NSString *)collectionIdentifier;
-(BOOL)isPlayable;
-(void)setHasITunesStoreAlbumArtistIdentifier:(BOOL)arg1 ;
-(NSString *)composer;
-(void)setHasStartTime:(BOOL)arg1 ;
-(void)setAlwaysLive:(BOOL)arg1 ;
-(void)setRadioStationName:(NSString *)arg1 ;
-(void)setAdvertisement:(BOOL)arg1 ;
-(BOOL)hasElapsedTimeTimestamp;
-(NSString *)contentIdentifier;
-(void)setLoading:(BOOL)arg1 ;
-(BOOL)hasLyricsAdamID;
-(BOOL)isResolvableParticipant;
-(void)setDownloadState:(long long)arg1 ;
-(long long)discNumber;
-(long long)editingStyleFlags;
-(void)setHasDuration:(BOOL)arg1 ;
-(void)setSeriesName:(NSString *)arg1 ;
-(void)setHasEditingStyleFlags:(BOOL)arg1 ;
-(void)setHasITunesStoreIdentifier:(BOOL)arg1 ;
-(unsigned long long)formatTierPreference;
-(BOOL)hasContainer;
-(NSString *)profileIdentifier;
-(void)setHasActiveFormatJustification:(BOOL)arg1 ;
-(void)setHasPlaybackRate:(BOOL)arg1 ;
-(BOOL)hasLoadingPlaceholderTitle;
-(void)setITunesStoreArtistIdentifier:(long long)arg1 ;
-(void)setInferredTimestamp:(double)arg1 ;
-(BOOL)hasEpisodeType;
-(NSDate *)releaseDate;
-(double)startTime;
-(BOOL)hasTotalDiscCount;
-(BOOL)hasSongTraits;
-(void)setParticipantName:(NSString *)arg1 ;
-(NSDictionary *)userInfo;
-(id)initWithProtobuf:(id)arg1 ;
-(long long)activeFormatJustification;
-(void)setITunesStoreIdentifier:(long long)arg1 ;
-(void)setITunesStoreSubscriptionIdentifier:(long long)arg1 ;
-(void)setHasPlaylistType:(BOOL)arg1 ;
-(long long)iTunesStoreAlbumArtistIdentifier;
-(NSDictionary *)dictionaryRepresentation;
-(void)setDefaultPlaybackRate:(float)arg1 ;
-(double)calculatedPlaybackPosition;
-(BOOL)hasITunesStoreAlbumIdentifier;
-(BOOL)isCurrentlyPlaying;
-(void)setStartTime:(double)arg1 ;
-(void)setDuration:(double)arg1 ;
-(BOOL)hasSharable;
-(NSData *)purchaseInfoData;
-(void)setIsResolvableParticipant:(BOOL)arg1 ;
-(void)setHasFormatTierPreference:(BOOL)arg1 ;
-(void)setSubtitle:(NSString *)arg1 ;
-(NSString *)radioStationString;
-(NSDictionary *)appMetrics;
-(BOOL)isSharable;
-(BOOL)hasArtworkDataWidthDeprecated;
-(void)setActiveFormatJustification:(long long)arg1 ;
-(void)setAlbumName:(NSString *)arg1 ;
-(void)setCurrentPlaybackDate:(NSDate *)arg1 ;
-(BOOL)hasActiveFormatJustification;
-(BOOL)hasExplicitItem;
-(BOOL)languageOptionsAvailable;
-(id)protobufWithEncoding:(long long)arg1 ;
-(void)setMediaSubType:(long long)arg1 ;
-(void)setHasDefaultPlaybackRate:(BOOL)arg1 ;
-(void)setHasEpisodeNumber:(BOOL)arg1 ;
-(NSURL *)assetURL;
-(void)setElapsedTimeTimestamp:(double)arg1 ;
-(void)setNowPlayingInfo:(NSDictionary *)arg1 ;
-(BOOL)hasCurrentlyPlaying;
-(void)setDeviceSpecificUserInfo:(NSDictionary *)arg1 ;
-(void)setHasRadioStationIdentifier:(BOOL)arg1 ;
-(BOOL)hasITunesStoreSubscriptionIdentifier;
-(BOOL)hasITunesStoreArtistIdentifier;
-(void)setSharable:(BOOL)arg1 ;
-(long long)radioStationIdentifier;
-(BOOL)hasRadioStationType;
-(void)setRadioStationString:(NSString *)arg1 ;
-(BOOL)hasDiscNumber;
-(float)downloadProgress;
-(void)setHasPlayable:(BOOL)arg1 ;
-(void)setRadioStationIdentifier:(long long)arg1 ;
-(NSString *)localizedDurationString;
-(void)setHasContainer:(BOOL)arg1 ;
-(BOOL)hasPlaybackRate;
-(void)setClassicalWork:(NSString *)arg1 ;
-(NSString *)durationStringLocalizationKey;
-(NSString *)subtitle;
-(NSString *)localizedContentRating;
-(void)setHasReportingAdamID:(BOOL)arg1 ;
-(void)setHasNumberOfSections:(BOOL)arg1 ;
-(void)setHasTotalTrackCount:(BOOL)arg1 ;
-(void)setHasAlwaysLive:(BOOL)arg1 ;
-(void)setStreamingContent:(BOOL)arg1 ;
-(BOOL)hasFormatTierPreference;
-(BOOL)hasAlwaysLive;
-(BOOL)isEqual:(id)arg1 ;
-(void)setHasTrackNumber:(BOOL)arg1 ;
-(void)setHasLiked:(BOOL)arg1 ;
-(void)setParticipantIdentifier:(NSString *)arg1 ;
-(NSURL *)artworkFileURL;
-(BOOL)hasDefaultPlaybackRate;
-(NSString *)title;
-(void)setRadioStationType:(long long)arg1 ;
-(void)setHasInWishList:(BOOL)arg1 ;
-(NSDictionary *)deviceSpecificUserInfo;
-(void)setPlaylistTraits:(unsigned long long)arg1 ;
-(void)mergeFrom:(id)arg1 ;
-(void)setDownloadProgress:(float)arg1 ;
-(void)setHasPlaylistTraits:(BOOL)arg1 ;
-(void)setPlaybackRate:(float)arg1 ;
-(void)setHasITunesStoreArtistIdentifier:(BOOL)arg1 ;
-(void)setHasSharable:(BOOL)arg1 ;
-(long long)legacyUniqueIdentifier;
-(void)setITunesStoreAlbumIdentifier:(long long)arg1 ;
-(NSString *)classicalWork;
-(void)setHasInfoAvailable:(BOOL)arg1 ;
-(void)setCurrentlyPlaying:(BOOL)arg1 ;
-(BOOL)isExplicitItem;
-(void)setArtworkURLTemplates:(NSArray *)arg1 ;
-(void)setHasExplicitItem:(BOOL)arg1 ;
-(long long)lyricsAdamID;
-(void)setHasLyricsAdamID:(BOOL)arg1 ;
-(MRContentItemMetadataAudioFormat *)preferredFormat;
-(void)setHasChapterCount:(BOOL)arg1 ;
-(long long)iTunesStoreSubscriptionIdentifier;
-(void)setChapterCount:(long long)arg1 ;
-(long long)episodeNumber;
-(void)setPreferredFormat:(MRContentItemMetadataAudioFormat *)arg1 ;
-(BOOL)hasReportingAdamID;
-(void)setLanguageOptionsAvailable:(BOOL)arg1 ;
-(BOOL)hasRadioStationIdentifier;
-(void)setHasElapsedTimeTimestamp:(BOOL)arg1 ;
-(void)setNumberOfSections:(long long)arg1 ;
-(void)setLyricsURL:(NSURL *)arg1 ;
-(void)setHasAdvertisement:(BOOL)arg1 ;
-(void)setLocalizedContentRating:(NSString *)arg1 ;
-(unsigned long long)albumTraits;
-(BOOL)hasPlaylistTraits;
-(void)setAlbumYear:(NSString *)arg1 ;
-(void)setHasTotalDiscCount:(BOOL)arg1 ;
-(long long)chapterCount;
-(BOOL)hasPlaybackProgress;
-(long long)artworkDataWidthDeprecated;
-(BOOL)hasAdvertisement;
-(void)setHasElapsedTime:(BOOL)arg1 ;
-(void)setLegacyUniqueIdentifier:(long long)arg1 ;
-(MRContentItemMetadataAudioFormat *)activeFormat;
-(NSString *)seriesName;
-(NSString *)albumName;
-(BOOL)hasLiked;
-(void)setPlaylistType:(long long)arg1 ;
-(void)setHasMediaSubType:(BOOL)arg1 ;
-(void)setHasDownloadProgress:(BOOL)arg1 ;
-(void)setContentIdentifier:(NSString *)arg1 ;
-(BOOL)hasDownloadState;
-(double)inferredTimestamp;
-(BOOL)isAdvertisement;
-(void)setAudioRoute:(MRContentItemMetadataAudioRoute *)arg1 ;
-(void)setUserInfo:(NSDictionary *)arg1 ;
-(void)setBrandIdentifier:(NSString *)arg1 ;
-(void)setHasLoading:(BOOL)arg1 ;
-(BOOL)hasInfoAvailable;
-(void)setHasLanguageOptionsAvailable:(BOOL)arg1 ;
-(void)setITunesStoreAlbumArtistIdentifier:(long long)arg1 ;
-(NSString *)artworkMIMEType;
-(void)setTotalTrackCount:(long long)arg1 ;
-(BOOL)hasSteerable;
-(void)setSteerable:(BOOL)arg1 ;
-(NSDictionary *)collectionInfo;
-(BOOL)hasTotalTrackCount;
-(BOOL)hasStreamingContent;
-(void)setEpisodeNumber:(long long)arg1 ;
-(BOOL)hasEpisodeNumber;
-(NSArray *)artworkURLTemplates;
-(void)setHasCurrentlyPlaying:(BOOL)arg1 ;
-(BOOL)lyricsAvailable;
-(double)elapsedTimeTimestamp;
-(BOOL)hasLyricsAvailable;
-(BOOL)hasInWishList;
-(BOOL)hasLoading;
-(NSArray *)alternativeFormats;
-(void)setArtworkDataHeightDeprecated:(long long)arg1 ;
-(void)setDurationStringLocalizationKey:(NSString *)arg1 ;
-(long long)mediaType;
-(NSDate *)currentPlaybackDate;
-(void)setHasITunesStoreAlbumIdentifier:(BOOL)arg1 ;
-(long long)seasonNumber;
-(long long)artworkDataHeightDeprecated;
-(void)setHasArtworkAvailable:(BOOL)arg1 ;
-(void)setCollectionInfo:(NSDictionary *)arg1 ;
-(void)setArtworkFileURL:(NSURL *)arg1 ;
-(double)duration;
-(void)setActiveFormat:(MRContentItemMetadataAudioFormat *)arg1 ;
-(void)setHasStreamingContent:(BOOL)arg1 ;
-(void)setHasRadioStationType:(BOOL)arg1 ;
-(void)setHasLegacyUniqueIdentifier:(BOOL)arg1 ;
-(id)description;
-(void)setLiked:(BOOL)arg1 ;
-(NSString *)directorName;
-(BOOL)isStreamingContent;
-(void)setEditingStyleFlags:(long long)arg1 ;
-(long long)radioStationType;
-(BOOL)hasArtworkDataHeightDeprecated;
-(void)setProfileIdentifier:(NSString *)arg1 ;
-(unsigned long long)playlistTraits;
-(NSString *)participantName;
-(BOOL)hasArtworkAvailable;
-(BOOL)hasIsResolvableParticipant;
-(BOOL)infoAvailable;
-(BOOL)hasInferredTimestamp;
-(double)calculatedPlaybackPositionFromDate:(id)arg1 ;
-(NSData *)data;
-(void)setHasDiscNumber:(BOOL)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)setTitle:(NSString *)arg1 ;
-(BOOL)hasPlayCount;
-(long long)totalTrackCount;
-(float)defaultPlaybackRate;
-(void)setArtworkDataWidthDeprecated:(long long)arg1 ;
-(long long)iTunesStoreAlbumIdentifier;
-(void)setAssetURL:(NSURL *)arg1 ;
-(void)setHasSteerable:(BOOL)arg1 ;
-(void)setAlternativeFormats:(NSArray *)arg1 ;
-(void)setTotalDiscCount:(long long)arg1 ;
-(BOOL)hasITunesStoreAlbumArtistIdentifier;
-(void)setInfoAvailable:(BOOL)arg1 ;
-(NSURL *)artworkURL;
-(void)setInWishList:(BOOL)arg1 ;
-(void)setHasITunesStoreSubscriptionIdentifier:(BOOL)arg1 ;
-(void)setHasSongTraits:(BOOL)arg1 ;
-(id)initWithData:(id)arg1 ;
-(NSString *)albumYear;
-(void)setAppMetrics:(NSDictionary *)arg1 ;
-(void)setLocalizedDurationString:(NSString *)arg1 ;
-(BOOL)hasAlbumTraits;
@end

